general:
  data_path: "../data/inflation/"
  data_path_colab: "/content/temporal-fusion-transformer/data/inflation/"
  model_path_local: "../model/model_cpi_colab.pt"
  csv_name: "cpi_target.csv"
  csv_list: [
        "nominal_wages_uy.csv",
        "commodities.csv",
        "cpi_br_arg.csv",
        "exchange_rate_uy.csv",
        "exchange_rate_br_arg.csv",
        "unemployment_rate_uy.csv"
    ]
  weights: {
    "alim_beb_no_alc": 26.0566,
    "beb_alc_tab_estup":  4.2936,
    "bienes_servicios_diversos": 6.3306,
    "comunicaciones": 3.358,
    "educacion": 3.1421,
    "muebles_art_hogar": 5.7320,
    "recreacion_cultura": 6.4918,
    "restaurantes_hoteles": 7.7021,
    "ropa_calzado": 5.3748,
    "salud": 7.7090,
    "transporte": 10.1316,
    "vivienda": 13.6778
  }

model:
  time_varying_known_categoricals: ["month"]
  time_varying_known_reals:   [
      'ims_pr',
      'Argentina',
      'Brasil',
      'er_eop',
#      'er_aop',
      'value_lag1',
      'value_lag6',
      'value_lag12',
      'ims_pr_lag1',
      'ims_pr_lag6',
      'ims_pr_lag12',
      'Argentina_lag1',
      'Argentina_lag6',
      'Argentina_lag12',
      'Brasil_lag1',
      'Brasil_lag6',
      'Brasil_lag12',
      'er_eop_lag1',
      'er_eop_lag6',
      'er_eop_lag12',
#      'er_aop_lag1',
#      'er_aop_lag6',
#      'er_aop_lag12'
  ]
  batch_size: 256
  max_epochs: 1000
  gpus: 1
  learning_rate: 0.001
  hidden_size: 150
  dropout: 0.2
  hidden_continuous_size: 80
  gradient_clip_val: 0.3
  max_prediction_length: 12
  max_encoder_length: 48
  cutoff: 0.70
  model_path: "/content/drive/MyDrive/Colab_Notebooks/model/model_cpi_colab.pt"

model_local:
  time_varying_known_categoricals: ["month"]
  time_varying_known_reals:   [
      'ims_pr',
      'Argentina',
      'Brasil',
      'er_eop',
#      'er_aop',
      'value_lag1',
      'value_lag6',
      'value_lag12',
      'ims_pr_lag1',
      'ims_pr_lag6',
      'ims_pr_lag12',
      'Argentina_lag1',
      'Argentina_lag6',
      'Argentina_lag12',
      'Brasil_lag1',
      'Brasil_lag6',
      'Brasil_lag12',
      'er_eop_lag1',
      'er_eop_lag6',
      'er_eop_lag12',
#      'er_aop_lag1',
#      'er_aop_lag6',
#      'er_aop_lag12'
  ]
  batch_size: 512
  max_epochs: 2
  gpus: 0
  learning_rate: 0.01
  hidden_size: 8
  dropout: 0.2
  hidden_continuous_size: 4
  gradient_clip_val: 0.3
  max_prediction_length: 12
  max_encoder_length: 48
  cutoff: 0.70
  model_path: "../model/model_cpi.pt"