general:
  data_path: "data"
  folder_list: [
      'realTweets',
      'realTraffic',
      'realKnownCause',
      'realAdExchange',
      'realAWSCloudwatch',
      'M4Hourly'
  ]
  scaler_path_nbeats: "/Volumes/GoogleDrive/My Drive/Colab_Notebooks/model/n_beats/scaler.pickle"
  model_path_nbeats: "/Volumes/GoogleDrive/My Drive/Colab_Notebooks/model/n_beats/n_beats.pickle"

model:
  lags: null
  sma: null
  time_varying_known_categoricals: [
      "hour",
      "month",
      "day_of_week",
      "day",
      "weekofyear"
  ]
  time_varying_known_reals: [ "time_idx" ]
  batch_size: 512
  max_epochs: 1000
  gpus: 1
  strategy: "ddp"
  learning_rate: 0.005
  hidden_size: 100
  dropout: 0.21387145479502692
  hidden_continuous_size: 50
  gradient_clip_val: 0.8397065210970555
  attention_head_size: 4
  lstm_layers: 4
  max_prediction_length: 24
  max_encoder_length: 48
  sample: "60min"
  cutoff: 0.70
  model_path: "/content/drive/MyDrive/Colab_Notebooks/model/tft.pt"
  hyperparameters_path: "/content/drive/MyDrive/Colab_Notebooks/model/tuning_study.pkl"

model_local:
  lags: null
  sma: null
  time_varying_known_categoricals: [
      "hour",
      "month",
      "day_of_week",
      "day",
      "weekofyear"
  ]
  time_varying_known_reals: [ "time_idx" ]
  batch_size: 1024
  max_epochs: 2
  gpus: 0
  learning_rate: 0.1
  hidden_size: 1
  dropout: 0.11
  hidden_continuous_size: 1
  gradient_clip_val: 0.1
  attention_head_size: 1
  lstm_layers: 1
  max_prediction_length: 24
  max_encoder_length: 48
  sample: "60min"
  cutoff: 0.70
  model_path: "model/temporal_fusion_transformer/tft_local.pt"
  hyperparameters_path: "model/temporal_fusion_transformer/tuning_study.pkl"

nbeats:
    input_chunk_length: 48
    output_chunk_length: 24
    num_stacks: 2
    num_blocks: 1
    num_layers: 2
    layer_widths: 128
    n_epochs: 100
    nr_epochs_val_period: 1
    batch_size: 2048
    model_name: 'nbeats_run'
    sample: "60min"
    cutoff: 0.70
    model_path: "/content/drive/MyDrive/Colab_Notebooks/model/n_beats/n_beats.pickle"
    scaler_path: "/content/drive/MyDrive/Colab_Notebooks/model/n_beats/scaler.pickle"

nbeats_local:
    input_chunk_length: 48
    output_chunk_length: 24
    num_stacks: 10
    num_blocks: 1
    num_layers: 4
    layer_widths: 300
    n_epochs: 5
    nr_epochs_val_period: 1
    batch_size: 2048
    model_name: 'nbeats_run'
    sample: "60min"
    cutoff: 0.70
    model_path: "model/n_beats/n_beats_local.pickle"
    scaler_path: "model/n_beats/scaler_local.pickle"
