general:
  data_path: "data"
  folder_list: [
      'realTweets'
  ]
model:
  batch_size: 1024
  max_epochs: 250
  gpus: 1
  learning_rate: 0.0001
  hidden_size: 100
  dropout: 0.2
  hidden_continuous_size: 40
  gradient_clip_val: 0.3
model_local:
  batch_size: 2048
  max_epochs: 2
  gpus: 0
  learning_rate: 0.1
  hidden_size: 8
  dropout: 0.2
  hidden_continuous_size: 4
  gradient_clip_val: 0.3