general:
  data_path: "data"
  folder_list: [
      'realTweets'
  ]
model:
  lags: None
  sma: [ 12 ]
  time_varying_known_categoricals: [
      "hour",
      "month",
      "day_of_week",
      "day",
      "weekofyear"
  ]
  time_varying_known_reals: [ "time_idx" ]
  batch_size: 512
  max_epochs: 300
  gpus: 1
  learning_rate: 0.0001
  hidden_size: 100
  dropout: 0.2
  hidden_continuous_size: 50
  gradient_clip_val: 0.3
  max_prediction_length: 24
  max_encoder_length: 48
  sample: "60min"
  cutoff: 0.70
  model_path: "/content/drive/MyDrive/Colab_Notebooks/model/tft.pt"
  scaler_path_nbeats: "/content/drive/MyDrive/Colab_Notebooks/model/scaler.pickle"
  model_path_nbeats: "/content/drive/MyDrive/Colab_Notebooks/model/n_beats.pickle"

model_local:
  lags: None
  sma: [ 12 ]
  time_varying_known_categoricals: [
      "hour",
      "month",
      "day_of_week",
      "day",
      "weekofyear"
  ]
  time_varying_known_reals: [ "time_idx" ]
  batch_size: 1024
  max_epochs: 4
  gpus: 0
  learning_rate: 0.01
  hidden_size: 8
  dropout: 0.2
  hidden_continuous_size: 4
  gradient_clip_val: 0.3
  max_prediction_length: 24
  max_encoder_length: 48
  sample: "60min"
  cutoff: 0.70
  model_path: "model/temporal_fusion_transformer/tft_local.pt"

nbeats:
    input_chunk_length: 48
    output_chunk_length: 24
    num_stacks: 10
    num_blocks: 1
    num_layers: 4
    layer_widths: 512
    n_epochs: 150
    nr_epochs_val_period: 1
    batch_size: 512
    model_name: 'nbeats_run'
    sample: "60min"
    cutoff: 0.70
    model_path: "/content/drive/MyDrive/Colab_Notebooks/model/n_beats/n_beats.pickle"
    scaler_path: "/content/drive/MyDrive/Colab_Notebooks/model/n_beats/scaler.pickle"

nbeats_local:
    input_chunk_length: 48
    output_chunk_length: 24
    num_stacks: 10
    num_blocks: 1
    num_layers: 4
    layer_widths: 300
    n_epochs: 5
    nr_epochs_val_period: 1
    batch_size: 2048
    model_name: 'nbeats_run'
    sample: "60min"
    cutoff: 0.70
    model_path: "model/n_beats/n_beats_local.pickle"
    scaler_path: "model/n_beats/scaler_local.pickle"
